version: 2.1

aliases:
  - &repo_cache_filename |
    repo-{{ .Environment.CIRCLE_SHA1 }}

  - &npm_cache_filename |
    {{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}

commands:
  install:
    parameters:
      install-commands:
        description: "Steps that will be executed before the tests"
        type: steps
        default: []
    steps:
      - checkout
      - save_cache:
          key: *repo_cache_filename
          paths:
            - /home/circleci/project/
      - restore_cache:
          key: *npm_cache_filename
      - run: node --version
      - run: npm --version
      - run: java -version
      - run: npm ci
      - save_cache:
          key: *npm_cache_filename
          paths:
            - /home/circleci/.npm
            - ./node_modules/

  run-tests:
    parameters:
      test-commands:
        description: "Steps that will be executed after the repo is cloned and dependencies are installed, but before tests are run"
        type: steps
        default: []
    steps:
      - restore_cache:
          key: *repo_cache_filename
      - steps: << parameters.test-commands >>

jobs:
  node-8:
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - install
      - run-tests:
          test-commands:
            - run:
                name: Run tests
                command: npm test

  node-10:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - install
      - run-tests:
          test-commands:
            - run:
                name: Run tests
                command: npm test
            - run:
                name: Run BrowserStack tests
                command: |
                  if [[ -z "$CIRCLE_PULL_REQUEST" && ! `git log --format=%B --no-merges -n 1 | grep '\[skip browser\]'` ]]; then
                    npm run js-test-cloud;
                  fi
            - run:
                name: Run docs links checking
                command: npm run linkinator
            - run:
                name: Run coveralls
                command: npm run coveralls
                when: on_success

workflows:
  version: 2
  test:
    jobs:
      - node-8
      - node-10
